import {
  BookOpen,
  FolderOpen,
  PanelRightClose,
  Pencil,
  Sparkles,
} from "lucide-react";

export const HELP_SCREENSHOTS = {
  "files-sidebar": new URL("../assets/help/screenshots/files-sidebar.webp", import.meta.url).href,
  "tabs-groups": new URL("../assets/help/screenshots/tabs-groups.webp", import.meta.url).href,
  "page-view": new URL("../assets/help/screenshots/page-view.webp", import.meta.url).href,
  "save-recovery": new URL("../assets/help/screenshots/save-recovery.webp", import.meta.url).href,
  "document-history": new URL("../assets/help/screenshots/document-history.webp", import.meta.url).href,
  interchange: new URL("../assets/help/screenshots/interchange.webp", import.meta.url).href,
  "profile-migration": new URL("../assets/help/screenshots/profile-migration.webp", import.meta.url).href,
  search: new URL("../assets/help/screenshots/search.webp", import.meta.url).href,
  "editor-outline": new URL("../assets/help/screenshots/editor-outline.webp", import.meta.url).href,
  "selection-links": new URL("../assets/help/screenshots/selection-links.webp", import.meta.url).href,
  "selection-ai-assistant": new URL("../assets/help/screenshots/selection-ai-assistant.webp", import.meta.url).href,
  comments: new URL("../assets/help/screenshots/comments.webp", import.meta.url).href,
  "comments-compose": new URL("../assets/help/screenshots/comments-compose.webp", import.meta.url).href,
  "comments-thread": new URL("../assets/help/screenshots/comments-thread.webp", import.meta.url).href,
  "media-pagination": new URL("../assets/help/screenshots/media-pagination.webp", import.meta.url).href,
  table: new URL("../assets/help/screenshots/table.webp", import.meta.url).href,
  "professional-content": new URL("../assets/help/screenshots/professional-content.webp", import.meta.url).href,
  "writing-assistance": new URL("../assets/help/screenshots/writing-assistance.webp", import.meta.url).href,
  "footnotes-citations": new URL("../assets/help/screenshots/footnotes-citations.webp", import.meta.url).href,
  "related-notes": new URL("../assets/help/screenshots/related-notes.webp", import.meta.url).href,
  "research-library": new URL("../assets/help/screenshots/research-library.webp", import.meta.url).href,
  "research-readers": new URL("../assets/help/screenshots/research-readers.webp", import.meta.url).href,
  "ai-modes": new URL("../assets/help/screenshots/ai-modes.webp", import.meta.url).href,
  "ai-compose": new URL("../assets/help/screenshots/ai-compose.webp", import.meta.url).href,
  "ai-model-chooser": new URL("../assets/help/screenshots/ai-model-chooser.webp", import.meta.url).href,
  "ai-providers": new URL("../assets/help/screenshots/ai-providers.webp", import.meta.url).href,
  "codex-cli": new URL("../assets/help/screenshots/codex-cli.webp", import.meta.url).href,
  "codex-cli-models": new URL("../assets/help/screenshots/codex-cli-models.webp", import.meta.url).href,
  "ai-optimize": new URL("../assets/help/screenshots/ai-optimize.webp", import.meta.url).href,
  "ai-optimize-apply": new URL("../assets/help/screenshots/ai-optimize-apply.webp", import.meta.url).href,
  "ai-chat": new URL("../assets/help/screenshots/ai-chat.webp", import.meta.url).href,
  "ai-isolation": new URL("../assets/help/screenshots/ai-isolation.webp", import.meta.url).href,
  "focus-mode": new URL("../assets/help/screenshots/focus-mode.webp", import.meta.url).href,
  "template-quick-menu": new URL("../assets/help/screenshots/template-quick-menu.webp", import.meta.url).href,
  "template-quick-picker": new URL("../assets/help/screenshots/template-quick-picker.webp", import.meta.url).href,
  "templates-gallery": new URL("../assets/help/screenshots/templates-gallery.webp", import.meta.url).href,
  "template-editor": new URL("../assets/help/screenshots/template-editor.webp", import.meta.url).href,
  "template-editor-advanced": new URL("../assets/help/screenshots/template-editor-advanced.webp", import.meta.url).href,
  "statusbar-update": new URL("../assets/help/screenshots/statusbar-update.webp", import.meta.url).href,
  "release-notes": new URL("../assets/help/screenshots/release-notes.webp", import.meta.url).href,
};

export const HELP_CATEGORIES = [
  { id: "files", label: "文件与组织", icon: FolderOpen },
  { id: "writing", label: "写作与结构", icon: Pencil },
  { id: "research", label: "资料与研究", icon: BookOpen },
  { id: "ai", label: "AI 功能", icon: Sparkles },
  { id: "view", label: "视图与设置", icon: PanelRightClose },
];

export { HELP_TOPICS } from "./help-topics.generated.js";
