const fs = require("node:fs");
const path = require("node:path");

const SOURCE_DIRECTORY = path.join(__dirname, "preload-src");
const OUTPUT_FILE = path.join(__dirname, "preload.cjs");
const ENTRY_MODULE = "facade.cjs";

function toModuleId(filePath) {
  return path.relative(SOURCE_DIRECTORY, filePath).split(path.sep).join("/");
}

function collectPreloadModules(directory = SOURCE_DIRECTORY) {
  const files = [];
  const pending = [path.resolve(directory)];
  while (pending.length > 0) {
    const current = pending.pop();
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const entryPath = path.join(current, entry.name);
      if (entry.isDirectory()) pending.push(entryPath);
      else if (entry.isFile() && entry.name.endsWith(".cjs")) files.push(entryPath);
    }
  }
  return files.sort((left, right) => toModuleId(left).localeCompare(toModuleId(right), "en"));
}

function localDependencies(moduleId, source, knownModuleIds) {
  const dependencies = {};
  const requirePattern = /\brequire\(\s*(["'])([^"']+)\1\s*\)/g;
  for (const match of source.matchAll(requirePattern)) {
    const request = match[2];
    if (!request.startsWith(".")) {
      throw new Error(`Sandbox preload source cannot require external module "${request}" from ${moduleId}`);
    }
    const resolved = path.posix.normalize(path.posix.join(path.posix.dirname(moduleId), request));
    if (!knownModuleIds.has(resolved)) {
      throw new Error(`Missing sandbox preload dependency "${request}" from ${moduleId}`);
    }
    dependencies[request] = resolved;
  }
  return dependencies;
}

function indentSource(source, spaces = 4) {
  const prefix = " ".repeat(spaces);
  return source.replace(/\r\n?/g, "\n").trimEnd().split("\n")
    .map((line) => (line ? `${prefix}${line}` : ""))
    .join("\n");
}

function createPreloadBundle() {
  const files = collectPreloadModules();
  const modules = files.map((filePath) => ({
    id: toModuleId(filePath),
    source: fs.readFileSync(filePath, "utf8"),
  }));
  const knownModuleIds = new Set(modules.map(({ id }) => id));
  if (!knownModuleIds.has(ENTRY_MODULE)) throw new Error(`Missing preload entry module: ${ENTRY_MODULE}`);

  const moduleFactories = modules.map(({ id, source }) => (
    `  ${JSON.stringify(id)}: function preloadModule(module, exports, require) {\n${indentSource(source)}\n  }`
  )).join(",\n");
  const dependencyMap = Object.fromEntries(modules.map(({ id, source }) => [
    id,
    localDependencies(id, source, knownModuleIds),
  ]));

  return `// This file is generated by build-preload.cjs from preload-src/. Do not edit it directly.\n`
    + `const __preloadModules = {\n${moduleFactories}\n};\n`
    + `const __preloadDependencies = ${JSON.stringify(dependencyMap, null, 2)};\n`
    + "const __preloadCache = Object.create(null);\n"
    + "function __loadPreloadModule(moduleId) {\n"
    + "  if (__preloadCache[moduleId]) return __preloadCache[moduleId].exports;\n"
    + "  const factory = __preloadModules[moduleId];\n"
    + "  if (!factory) throw new Error(`Unknown bundled preload module: ${moduleId}`);\n"
    + "  const module = { exports: {} };\n"
    + "  __preloadCache[moduleId] = module;\n"
    + "  factory(module, module.exports, (request) => {\n"
    + "    const dependencyId = __preloadDependencies[moduleId]?.[request];\n"
    + "    if (!dependencyId) throw new Error(`Unknown bundled preload dependency: ${moduleId} -> ${request}`);\n"
    + "    return __loadPreloadModule(dependencyId);\n"
    + "  });\n"
    + "  return module.exports;\n"
    + "}\n\n"
    + "const { contextBridge, ipcRenderer } = require(\"electron\");\n"
    + `const { createPaperWriterApi } = __loadPreloadModule(${JSON.stringify(ENTRY_MODULE)});\n`
    + "const flatFacade = createPaperWriterApi(ipcRenderer);\n"
    + "contextBridge.exposeInMainWorld(\"paperWriter\", flatFacade);\n";
}

function checkPreloadBundle() {
  const expected = createPreloadBundle();
  const actual = fs.existsSync(OUTPUT_FILE) ? fs.readFileSync(OUTPUT_FILE, "utf8") : "";
  if (actual !== expected) {
    throw new Error("preload.cjs is stale. Run `npm run preload:build` in apps/writer/electron.");
  }
  return OUTPUT_FILE;
}

function writePreloadBundle() {
  fs.writeFileSync(OUTPUT_FILE, createPreloadBundle(), "utf8");
  return OUTPUT_FILE;
}

if (require.main === module) {
  if (process.argv.includes("--check")) {
    checkPreloadBundle();
    console.log("Preload bundle is up to date.");
  } else {
    writePreloadBundle();
    console.log("Built sandbox-compatible preload.cjs.");
  }
}

module.exports = {
  checkPreloadBundle,
  collectPreloadModules,
  createPreloadBundle,
  writePreloadBundle,
};
