// This file is generated by build-preload.cjs from preload-src/. Do not edit it directly.
const __preloadModules = {
  "ai-api.cjs": function preloadModule(module, exports, require) {
    const { subscribeToIpc } = require("./subscriptions.cjs");

    function createAiApi(ipcRenderer) {
      return {
        getAiConfig: () => ipcRenderer.invoke("ai:get-config"),
        refreshCodexCliStatus: () => ipcRenderer.invoke("ai:refresh-codex"),
        startCodexCliLogin: () => ipcRenderer.invoke("ai:start-codex-login"),
        createAiProvider: (provider) => ipcRenderer.invoke("ai:create-provider", provider || {}),
        deleteAiProvider: (providerId) => ipcRenderer.invoke("ai:delete-provider", providerId || ""),
        saveAiConfig: (config) => ipcRenderer.invoke("ai:save-config", config || {}),
        testAiConfig: (config) => ipcRenderer.invoke("ai:test-config", config || {}),
        generateAi: (payload) => ipcRenderer.invoke("ai:generate", payload || {}),
        generateSelectionAi: (payload) => ipcRenderer.invoke("ai:selection-generate", payload || {}),
        resolveAiApply: (payload) => ipcRenderer.invoke("ai:resolve-apply", payload || {}),
        cancelAi: (requestId) => ipcRenderer.invoke("ai:cancel", requestId || ""),
        exportAiChat: (payload) => ipcRenderer.invoke("ai:export-chat", payload || {}),
        routeAiCollaboration: (payload) => ipcRenderer.invoke("ai-collaboration:route", payload || {}),
        planAiCollaboration: (payload) => ipcRenderer.invoke("ai-collaboration:plan", payload || {}),
        cancelAiCollaboration: (requestId) => ipcRenderer.invoke("ai-collaboration:cancel", requestId || ""),
        validateAiCollaborationProposal: (payload) => ipcRenderer.invoke("ai-collaboration:validate", payload || {}),
        prepareAiCollaborationCommit: (payload) => ipcRenderer.invoke("ai-collaboration:prepare", payload || {}),
        commitAiCollaboration: (commitId) => ipcRenderer.invoke("ai-collaboration:commit", commitId || ""),
        abortAiCollaborationCommit: (commitId) => ipcRenderer.invoke("ai-collaboration:abort", commitId || ""),
        getHelpAssistantState: () => ipcRenderer.invoke("help-ai:get-state"),
        createHelpAssistantSession: () => ipcRenderer.invoke("help-ai:create-session"),
        setActiveHelpAssistantSession: (sessionId) => ipcRenderer.invoke("help-ai:set-active-session", sessionId || ""),
        renameHelpAssistantSession: (payload) => ipcRenderer.invoke("help-ai:rename-session", payload || {}),
        deleteHelpAssistantSession: (sessionId) => ipcRenderer.invoke("help-ai:delete-session", sessionId || ""),
        generateHelpAssistant: (payload) => ipcRenderer.invoke("help-ai:generate", payload || {}),
        cancelHelpAssistant: (requestId) => ipcRenderer.invoke("help-ai:cancel", requestId || ""),
        translateResearchContent: (payload) => ipcRenderer.invoke("research-translation:translate", payload || {}),
        cancelResearchTranslation: (requestId) => ipcRenderer.invoke("research-translation:cancel", requestId || ""),
        onAiChunk: (callback) => subscribeToIpc(ipcRenderer, "ai:chunk", callback),
        onAiDone: (callback) => subscribeToIpc(ipcRenderer, "ai:done", callback),
        onAiError: (callback) => subscribeToIpc(ipcRenderer, "ai:error", callback),
        onAiCollaborationEvent: (callback) => subscribeToIpc(ipcRenderer, "ai-collaboration:event", callback),
        onHelpAssistantChunk: (callback) => subscribeToIpc(ipcRenderer, "help-ai:chunk", callback),
        onHelpAssistantDone: (callback) => subscribeToIpc(ipcRenderer, "help-ai:done", callback),
        onHelpAssistantError: (callback) => subscribeToIpc(ipcRenderer, "help-ai:error", callback),
        onResearchTranslationProgress: (callback) => subscribeToIpc(ipcRenderer, "research-translation:progress", callback),
        onCodexCliStatus: (callback) => subscribeToIpc(ipcRenderer, "ai:codex-status", callback),
      };
    }

    module.exports = {
      createAiApi,
    };
  },
  "citation-api.cjs": function preloadModule(module, exports, require) {
    function createCitationApi(ipcRenderer) {
      return {
        parseCitations: (payload) => ipcRenderer.invoke("citation:parse", payload || {}),
        exportCitations: (payload) => ipcRenderer.invoke("citation:export", payload || {}),
        formatCitations: (payload) => ipcRenderer.invoke("citation:format", payload || {}),
        listCitationStyles: () => ipcRenderer.invoke("citation:styles"),
        validateCslStyle: (payload) => ipcRenderer.invoke("citation:validate-style", payload || {}),
        pickCitationStyle: () => ipcRenderer.invoke("citation:pick-style"),
        lookupCitation: (payload) => ipcRenderer.invoke("citation:lookup", payload || {}),
        pickCitationImport: (payload) => ipcRenderer.invoke("citation:pick-import", payload || {}),
        saveCitationExport: (payload) => ipcRenderer.invoke("citation:save-export", payload || {}),
        listPublicCitations: () => ipcRenderer.invoke("citation:public-list"),
        upsertPublicCitation: (source) => ipcRenderer.invoke("citation:public-upsert", source || {}),
        deletePublicCitation: (sourceId) => ipcRenderer.invoke("citation:public-delete", sourceId || ""),
        migrateWorkspaceCitationsToPublic: (workspacePath) => (
          ipcRenderer.invoke("citation:public-migrate", workspacePath || "")
        ),
      };
    }

    module.exports = {
      createCitationApi,
    };
  },
  "composition-api.cjs": function preloadModule(module, exports, require) {
    const { subscribeToIpc } = require("./subscriptions.cjs");

    function createCompositionApi(ipcRenderer) {
      return {
        listCompositionJobs: () => ipcRenderer.invoke("composition:list"),
        getCompositionJob: (jobId) => ipcRenderer.invoke("composition:get", jobId || ""),
        createCompositionJob: (payload) => ipcRenderer.invoke("composition:create", payload || {}),
        updateCompositionJob: (payload) => ipcRenderer.invoke("composition:update", payload || {}),
        deleteCompositionJob: (jobId) => ipcRenderer.invoke("composition:delete", jobId || ""),
        generateCompositionOutline: (payload) => ipcRenderer.invoke("composition:generate-outline", payload || {}),
        generateCompositionSection: (payload) => ipcRenderer.invoke("composition:generate-section", payload || {}),
        reviewComposition: (payload) => ipcRenderer.invoke("composition:review", payload || {}),
        pauseComposition: (jobId) => ipcRenderer.invoke("composition:pause", jobId || ""),
        resumeComposition: (payload) => ipcRenderer.invoke("composition:resume", payload || {}),
        cancelComposition: (jobId) => ipcRenderer.invoke("composition:cancel", jobId || ""),
        finalizeComposition: (payload) => ipcRenderer.invoke("composition:finalize", payload || {}),
        onCompositionEvent: (callback) => subscribeToIpc(ipcRenderer, "composition:event", callback),
      };
    }

    module.exports = {
      createCompositionApi,
    };
  },
  "document-api.cjs": function preloadModule(module, exports, require) {
    const { subscribeToIpc } = require("./subscriptions.cjs");

    const MAX_PROFESSIONAL_RENDERED_HTML_CHARS = 48 * 1024 * 1024;

    function createDocumentApi(ipcRenderer) {
      return {
        openDocument: () => ipcRenderer.invoke("document:open"),
        openDocumentPath: (filePath) => ipcRenderer.invoke("document:open-path", filePath || ""),
        importDocument: () => ipcRenderer.invoke("document:import"),
        exportEditable: (document, format, targetPath = "", renderedHtml = "") => {
          const transientHtml = ["docx", "html"].includes(format) && typeof renderedHtml === "string"
            ? renderedHtml
            : "";
          if (transientHtml.length > MAX_PROFESSIONAL_RENDERED_HTML_CHARS) {
            return Promise.reject(new Error("专业内容临时渲染结果超过 IPC 安全上限"));
          }
          return ipcRenderer.invoke("document:export-editable", {
            document: document || {},
            format: format || "",
            targetPath: targetPath || "",
            renderedHtml: transientHtml,
          });
        },
        getDocumentRevision: (filePath) => ipcRenderer.invoke("document:revision", filePath || ""),
        regenerateDocumentIdentity: (filePath, force = false) => (
          ipcRenderer.invoke("document:regenerate-identity", filePath || "", Boolean(force))
        ),
        backupDocument: (filePath) => ipcRenderer.invoke("document:backup", filePath || ""),
        saveDocument: (document, currentPath, saveAs = false, reservedPaths = [], expectedRevision = null, options = {}) =>
          ipcRenderer.invoke(
            "document:save",
            document,
            currentPath || "",
            Boolean(saveAs),
            Array.isArray(reservedPaths)
              ? reservedPaths.filter((value) => typeof value === "string").slice(0, 100).map((value) => value.slice(0, 32768))
              : [],
            expectedRevision || null,
            options && typeof options === "object" ? options : {},
          ),
        saveTempDocument: (document, tabId) => ipcRenderer.invoke("autosave:save-tab", document, tabId || ""),
        deleteTempDocument: (tabId) => ipcRenderer.invoke("autosave:delete-tab", tabId || ""),
        pickExportPath: (format, suggestedName, initialDirectory) => (
          ipcRenderer.invoke(
            "document:pick-export-path",
            ["images", "pdf", "markdown", "html", "txt", "docx"].includes(format) ? format : "pdf",
            suggestedName || "未命名信笺",
            typeof initialDirectory === "string" ? initialDirectory.slice(0, 32768) : "",
          )
        ),
        exportPdf: (suggestedName, targetPath) => (
          ipcRenderer.invoke("document:export-pdf", suggestedName || "未命名信笺", targetPath || "")
        ),
        exportPageImages: (suggestedName, pageRects, targetPath) => (
          ipcRenderer.invoke(
            "document:export-page-images",
            suggestedName || "未命名信笺",
            Array.isArray(pageRects) ? pageRects : [],
            targetPath || "",
          )
        ),
        onExportProgress: (callback) => subscribeToIpc(ipcRenderer, "document:export-progress", callback),
        pickImage: () => ipcRenderer.invoke("asset:pick-image"),
        pickAudio: () => ipcRenderer.invoke("asset:pick-audio"),
        pickVideo: () => ipcRenderer.invoke("asset:pick-video"),
        writeClipboardContent: (payload) => (
          ipcRenderer.invoke("clipboard:write-content", payload && typeof payload === "object" ? payload : {})
        ),
        copyImageReference: (payload) => (
          ipcRenderer.invoke("clipboard:write-image-reference", payload && typeof payload === "object" ? payload : {})
        ),
        openExternal: (url) => ipcRenderer.invoke("external:open", url),
        loadAutosave: () => ipcRenderer.invoke("autosave:load"),
        saveAutosave: (document) => ipcRenderer.invoke("autosave:save", document),
        clearAutosave: () => ipcRenderer.invoke("autosave:clear"),
      };
    }

    module.exports = {
      createDocumentApi,
    };
  },
  "facade.cjs": function preloadModule(module, exports, require) {
    const { createAiApi } = require("./ai-api.cjs");
    const { createCitationApi } = require("./citation-api.cjs");
    const { createCompositionApi } = require("./composition-api.cjs");
    const { createDocumentApi } = require("./document-api.cjs");
    const { createHistoryApi } = require("./history-api.cjs");
    const { createProfileApi } = require("./profile-api.cjs");
    const { createResearchApi } = require("./research-api.cjs");
    const { createWindowUpdateApi } = require("./window-update-api.cjs");
    const { createWorkspaceApi } = require("./workspace-api.cjs");
    const { createWritingAssistanceApi } = require("./writing-assistance-api.cjs");

    function createPaperWriterApi(ipcRenderer) {
      return {
        isElectron: true,
        ...createWindowUpdateApi(ipcRenderer),
        ...createAiApi(ipcRenderer),
        ...createCompositionApi(ipcRenderer),
        ...createCitationApi(ipcRenderer),
        ...createDocumentApi(ipcRenderer),
        ...createHistoryApi(ipcRenderer),
        ...createProfileApi(ipcRenderer),
        ...createWorkspaceApi(ipcRenderer),
        ...createResearchApi(ipcRenderer),
        ...createWritingAssistanceApi(ipcRenderer),
      };
    }

    module.exports = {
      createPaperWriterApi,
    };
  },
  "history-api.cjs": function preloadModule(module, exports, require) {
    function createHistoryApi(ipcRenderer) {
      return {
        listDocumentHistory: (documentId, currentSha256 = "") => (
          currentSha256
            ? ipcRenderer.invoke("history:list", documentId || "", currentSha256)
            : ipcRenderer.invoke("history:list", documentId || "")
        ),
        readDocumentHistory: (payload) => ipcRenderer.invoke("history:read", payload || {}),
        createDocumentHistory: (payload) => ipcRenderer.invoke("history:create", payload || {}),
        updateDocumentHistory: (payload) => ipcRenderer.invoke("history:pin", payload || {}),
        deleteDocumentHistory: (payload) => ipcRenderer.invoke("history:delete", payload || {}),
        restoreDocumentHistory: (payload) => ipcRenderer.invoke("history:restore", payload || {}),
        clearAutomaticDocumentHistory: (documentId) => ipcRenderer.invoke("history:clear-auto", documentId || ""),
        clearDocumentHistory: (documentId) => ipcRenderer.invoke("history:clear", documentId || ""),
      };
    }

    module.exports = {
      createHistoryApi,
    };
  },
  "profile-api.cjs": function preloadModule(module, exports, require) {
    function createProfileApi(ipcRenderer) {
      return {
        exportProfile: (payload) => ipcRenderer.invoke("profile:export", payload || {}),
        inspectProfile: (payload) => ipcRenderer.invoke("profile:inspect", payload || {}),
        verifyProfile: (payload) => ipcRenderer.invoke("profile:verify", payload || {}),
        importProfile: (payload) => ipcRenderer.invoke("profile:import", payload || {}),
        commitProfileImport: (payload) => ipcRenderer.invoke("profile:commit", payload || {}),
        rollbackProfileImport: (payload) => ipcRenderer.invoke("profile:rollback", payload || {}),
      };
    }

    module.exports = {
      createProfileApi,
    };
  },
  "research-api.cjs": function preloadModule(module, exports, require) {
    const { subscribeToIpc } = require("./subscriptions.cjs");

    function sanitizeLegacyResearchSource(source) {
      const sanitized = source && typeof source === "object" && !Array.isArray(source) ? { ...source } : {};
      delete sanitized.filePath;
      return sanitized;
    }

    function createResearchApi(ipcRenderer) {
      return {
        showResearchWebView: (payload) => ipcRenderer.invoke("research:web-view-show", payload || {}),
        updateResearchWebViewBounds: (payload) => ipcRenderer.invoke("research:web-view-bounds", payload || {}),
        hideResearchWebView: (viewId = "") => ipcRenderer.invoke("research:web-view-hide", viewId || ""),
        controlResearchWebView: (viewId, action) => ipcRenderer.invoke("research:web-view-control", {
          viewId: viewId || "",
          action: action || "",
        }),
        destroyResearchWebView: (viewId) => ipcRenderer.invoke("research:web-view-destroy", viewId || ""),
        onResearchWebViewState: (callback) => subscribeToIpc(ipcRenderer, "research:web-view-state", callback),
        getResearchRoot: () => ipcRenderer.invoke("research:root-get"),
        pickResearchRoot: () => ipcRenderer.invoke("research:root-pick"),
        clearResearchRoot: () => ipcRenderer.invoke("research:root-clear"),
        listResearchFolder: (libraryId, relativePath = "") => ipcRenderer.invoke("research:folder-list", {
          libraryId: libraryId || "",
          relativePath: relativePath || "",
        }),
        createResearchFolder: (libraryId, parentRelativePath = "", name = "") => (
          ipcRenderer.invoke("research:folder-create", {
            libraryId: libraryId || "",
            parentRelativePath: parentRelativePath || "",
            name: name || "",
          })
        ),
        importResearchFiles: (libraryId, targetRelativePath = "") => ipcRenderer.invoke("research:file-import", {
          libraryId: libraryId || "",
          targetRelativePath: targetRelativePath || "",
        }),
        renameResearchEntry: (libraryId, relativePath, nextName) => ipcRenderer.invoke("research:entry-rename", {
          libraryId: libraryId || "",
          relativePath: relativePath || "",
          nextName: nextName || "",
        }),
        moveResearchEntry: (libraryId, relativePath, targetFolderRelativePath = "") => (
          ipcRenderer.invoke("research:entry-move", {
            libraryId: libraryId || "",
            relativePath: relativePath || "",
            targetFolderRelativePath: targetFolderRelativePath || "",
          })
        ),
        trashResearchEntry: (libraryId, relativePath) => ipcRenderer.invoke("research:entry-trash", {
          libraryId: libraryId || "",
          relativePath: relativePath || "",
        }),
        showResearchEntry: (libraryId, relativePath = "") => ipcRenderer.invoke("research:entry-show", {
          libraryId: libraryId || "",
          relativePath: relativePath || "",
        }),
        copyResearchEntryPath: (libraryId, relativePath = "") => ipcRenderer.invoke("research:entry-copy-path", {
          libraryId: libraryId || "",
          relativePath: relativePath || "",
        }),
        listResearchLibrarySources: (libraryId) => (
          ipcRenderer.invoke("research:source-list", { libraryId: libraryId || "" })
        ),
        listResearchWebTree: (libraryId) => ipcRenderer.invoke("research:web-tree-list", { libraryId: libraryId || "" }),
        upsertResearchWebSource: (libraryId, source, placement, revisions = {}) => (
          ipcRenderer.invoke("research:web-source-upsert", {
            libraryId: libraryId || "",
            source: source && typeof source === "object" ? source : {},
            placement: placement && typeof placement === "object" ? placement : { scopeKey: "global", folderId: "" },
            revisions: revisions && typeof revisions === "object" ? revisions : {},
          })
        ),
        createResearchWebFolder: (libraryId, folder, expectedRevision = null) => (
          ipcRenderer.invoke("research:web-folder-create", {
            libraryId: libraryId || "",
            folder: folder && typeof folder === "object" ? folder : {},
            expectedRevision: expectedRevision || null,
          })
        ),
        updateResearchWebFolder: (libraryId, folder, expectedRevision = null) => (
          ipcRenderer.invoke("research:web-folder-update", {
            libraryId: libraryId || "",
            folder: folder && typeof folder === "object" ? folder : {},
            expectedRevision: expectedRevision || null,
          })
        ),
        deleteResearchWebFolder: (libraryId, folderId, expectedRevision = null) => (
          ipcRenderer.invoke("research:web-folder-delete", {
            libraryId: libraryId || "",
            folderId: folderId || "",
            expectedRevision: expectedRevision || null,
          })
        ),
        moveResearchWebSource: (libraryId, sourceId, placement, expectedRevision = null) => (
          ipcRenderer.invoke("research:web-source-move", {
            libraryId: libraryId || "",
            sourceId: sourceId || "",
            placement: placement && typeof placement === "object" ? placement : { scopeKey: "global", folderId: "" },
            expectedRevision: expectedRevision || null,
          })
        ),
        copyResearchWebSelection: (libraryId, selection = {}) => (
          ipcRenderer.invoke("research:web-selection-copy", {
            libraryId: libraryId || "",
            selection: selection && typeof selection === "object" ? selection : {},
          })
        ),
        upsertResearchLibrarySource: (libraryId, source, expectedRevision = null) => (
          ipcRenderer.invoke("research:source-upsert", {
            libraryId: libraryId || "",
            source: source && typeof source === "object" ? source : {},
            expectedRevision: expectedRevision || null,
          })
        ),
        deleteResearchLibrarySource: (libraryId, sourceId, expectedRevision = null) => (
          ipcRenderer.invoke("research:source-delete", {
            libraryId: libraryId || "",
            sourceId: sourceId || "",
            expectedRevision: expectedRevision || null,
          })
        ),
        importLegacyResearch: (workspacePath, libraryId) => ipcRenderer.invoke("research:legacy-import", {
          workspacePath: workspacePath || "",
          libraryId: libraryId || "",
        }),
        readResearchPdf: (libraryId, relativePath) => ipcRenderer.invoke("research:pdf-read", {
          libraryId: libraryId || "",
          relativePath: relativePath || "",
        }),
        readResearchPreview: (libraryId, relativePath) => ipcRenderer.invoke("research:preview-read", {
          libraryId: libraryId || "",
          relativePath: relativePath || "",
        }),
        searchResearch: (payload = {}) => ipcRenderer.invoke("research:search", {
          libraryId: payload?.libraryId || "",
          requestId: payload?.requestId || "",
          query: payload?.query || "",
          scopeKey: payload?.scopeKey || "global",
          workspaceScopeKey: payload?.workspaceScopeKey || "",
          limit: payload?.limit,
          includeFiles: payload?.includeFiles !== false,
          includeWeb: payload?.includeWeb !== false,
          kinds: Array.isArray(payload?.kinds) ? payload.kinds : [],
        }),
        cancelResearchSearch: (libraryId, requestId) => (
          ipcRenderer.invoke("research:search-cancel", {
            libraryId: libraryId || "",
            requestId: requestId || "",
          })
        ),
        openResearchDocument: (libraryId, relativePath) => ipcRenderer.invoke("research:document-open", {
          libraryId: libraryId || "",
          relativePath: relativePath || "",
        }),
        openResearchEntryExternal: (libraryId, relativePath) => ipcRenderer.invoke("research:open-external", {
          libraryId: libraryId || "",
          relativePath: relativePath || "",
        }),
        watchResearchLibrary: (libraryId) => ipcRenderer.invoke("research:watch", { libraryId: libraryId || "" }),
        listResearch: (workspacePath) => ipcRenderer.invoke("research:list", workspacePath || ""),
        createResearch: (workspacePath, source) => ipcRenderer.invoke(
          "research:create",
          workspacePath || "",
          sanitizeLegacyResearchSource(source),
        ),
        updateResearch: (workspacePath, sourceId, patch) => (
          ipcRenderer.invoke("research:update", workspacePath || "", sourceId || "", patch || {})
        ),
        deleteResearch: (workspacePath, sourceId) => (
          ipcRenderer.invoke("research:delete", workspacePath || "", sourceId || "")
        ),
        relinkResearch: (workspacePath, sourceId) => (
          ipcRenderer.invoke("research:relink", workspacePath || "", sourceId || "")
        ),
        readResearchFile: (workspacePath, sourceId) => (
          ipcRenderer.invoke("research:read-file", workspacePath || "", sourceId || "")
        ),
        openResearchExternal: (workspacePath, sourceId) => (
          ipcRenderer.invoke("research:open-external", workspacePath || "", sourceId || "")
        ),
        listCitations: (workspacePath) => ipcRenderer.invoke("citation:list", workspacePath || ""),
        upsertCitation: (workspacePath, source) => (
          ipcRenderer.invoke("citation:upsert", workspacePath || "", source || {})
        ),
        deleteCitation: (workspacePath, sourceId) => (
          ipcRenderer.invoke("citation:delete", workspacePath || "", sourceId || "")
        ),
        onResearchLibraryChanged: (callback) => subscribeToIpc(ipcRenderer, "research:changed", callback, true),
        onResearchLibraryWatchError: (callback) => subscribeToIpc(ipcRenderer, "research:watch-error", callback, true),
        onResearchSearchProgress: (callback) => (
          subscribeToIpc(ipcRenderer, "research:search-progress", callback, true)
        ),
      };
    }

    module.exports = {
      createResearchApi,
      sanitizeLegacyResearchSource,
    };
  },
  "subscriptions.cjs": function preloadModule(module, exports, require) {
    function subscribeToIpc(ipcRenderer, channel, callback, emptyObjectFallback = false) {
      if (typeof callback !== "function") return () => {};
      const listener = (_event, payload) => callback(emptyObjectFallback ? (payload || {}) : payload);
      ipcRenderer.on(channel, listener);
      return () => ipcRenderer.removeListener(channel, listener);
    }

    module.exports = {
      subscribeToIpc,
    };
  },
  "window-update-api.cjs": function preloadModule(module, exports, require) {
    const { subscribeToIpc } = require("./subscriptions.cjs");

    function createWindowUpdateApi(ipcRenderer) {
      return {
        getPaths: () => ipcRenderer.invoke("app:get-paths"),
        debugLog: (event, data) => ipcRenderer.invoke("debug:log", event || "renderer", data || {}),
        setWindowModalOverlay: (active) => ipcRenderer.invoke("window:set-modal-overlay", Boolean(active)),
        setFullscreen: (fullscreen) => ipcRenderer.invoke("window:set-fullscreen", Boolean(fullscreen)),
        getFullscreen: () => ipcRenderer.invoke("window:get-fullscreen"),
        getUpdateState: () => ipcRenderer.invoke("update:get-state"),
        checkForUpdates: () => ipcRenderer.invoke("update:check"),
        downloadUpdate: () => ipcRenderer.invoke("update:download"),
        installUpdate: () => ipcRenderer.invoke("update:install"),
        onUpdateState: (callback) => subscribeToIpc(ipcRenderer, "update:state", callback),
        confirmClose: (payload) => ipcRenderer.invoke("app:confirm-close", payload || {}),
        closeReady: (payload) => ipcRenderer.invoke("app:close-ready", payload || {}),
        closeCanceled: (payload) => ipcRenderer.invoke("app:close-canceled", payload || {}),
        onCloseRequest: (callback) => subscribeToIpc(ipcRenderer, "app:close-request", callback, true),
        onWindowFocus: (callback) => subscribeToIpc(ipcRenderer, "window:focus", callback, true),
        onWindowBlur: (callback) => subscribeToIpc(ipcRenderer, "window:blur", callback, true),
        onFullscreenChanged: (callback) => (
          subscribeToIpc(ipcRenderer, "window:fullscreen-changed", callback, true)
        ),
      };
    }

    module.exports = {
      createWindowUpdateApi,
    };
  },
  "workspace-api.cjs": function preloadModule(module, exports, require) {
    const { subscribeToIpc } = require("./subscriptions.cjs");

    function createWorkspaceApi(ipcRenderer) {
      return {
        openFolder: () => ipcRenderer.invoke("folder:open"),
        listFolder: (folderPath) => ipcRenderer.invoke("folder:list", folderPath || ""),
        searchFolder: (payload) => ipcRenderer.invoke("folder:search", payload || {}),
        cancelFolderSearch: (folderPath, requestId) => (
          ipcRenderer.invoke("folder:search-cancel", folderPath || "", requestId || "")
        ),
        getWorkspaceRelationships: (payload) => ipcRenderer.invoke("workspace:relationships", payload || {}),
        watchWorkspace: (folderPath) => ipcRenderer.invoke("workspace:watch", folderPath || ""),
        copyFolderPath: (folderPath) => ipcRenderer.invoke("folder:copy-path", folderPath || ""),
        showFolder: (folderPath) => ipcRenderer.invoke("folder:show", folderPath || ""),
        createFolder: (parentPath, name) => ipcRenderer.invoke("folder:create", parentPath || "", name || ""),
        createDocumentInFolder: (folderPath, title, templateDocument) => (
          ipcRenderer.invoke("document:create-in-folder", folderPath || "", title || "", templateDocument || {})
        ),
        renameEntry: (targetPath, nextName) => ipcRenderer.invoke("entry:rename", targetPath || "", nextName || ""),
        deleteEntry: (targetPath) => ipcRenderer.invoke("entry:delete", targetPath || ""),
        moveEntry: (sourcePath, targetFolderPath) => (
          ipcRenderer.invoke("entry:move", sourcePath || "", targetFolderPath || "")
        ),
        getWorkspaceIdentity: (workspacePath) => ipcRenderer.invoke("workspace:identity", workspacePath || ""),
        onWorkspaceChanged: (callback) => subscribeToIpc(ipcRenderer, "workspace:changed", callback, true),
        onWorkspaceWatchError: (callback) => subscribeToIpc(ipcRenderer, "workspace:watch-error", callback, true),
      };
    }

    module.exports = {
      createWorkspaceApi,
    };
  },
  "writing-assistance-api.cjs": function preloadModule(module, exports, require) {
    const { subscribeToIpc } = require("./subscriptions.cjs");

    function createWritingAssistanceApi(ipcRenderer) {
      return {
        getWritingAssistance: () => ipcRenderer.invoke("writing-assistance:get"),
        saveWritingAssistance: (patch) => ipcRenderer.invoke("writing-assistance:save", patch || {}),
        addWritingDictionaryWord: (word) => ipcRenderer.invoke("writing-assistance:add-word", word || ""),
        removeWritingDictionaryWord: (word) => ipcRenderer.invoke("writing-assistance:remove-word", word || ""),
        onDocumentContextMenuRequest: (callback) => (
          subscribeToIpc(
            ipcRenderer,
            "writing-assistance:document-context-menu",
            callback,
            true,
          )
        ),
      };
    }

    module.exports = {
      createWritingAssistanceApi,
    };
  }
};
const __preloadDependencies = {
  "ai-api.cjs": {
    "./subscriptions.cjs": "subscriptions.cjs"
  },
  "citation-api.cjs": {},
  "composition-api.cjs": {
    "./subscriptions.cjs": "subscriptions.cjs"
  },
  "document-api.cjs": {
    "./subscriptions.cjs": "subscriptions.cjs"
  },
  "facade.cjs": {
    "./ai-api.cjs": "ai-api.cjs",
    "./citation-api.cjs": "citation-api.cjs",
    "./composition-api.cjs": "composition-api.cjs",
    "./document-api.cjs": "document-api.cjs",
    "./history-api.cjs": "history-api.cjs",
    "./profile-api.cjs": "profile-api.cjs",
    "./research-api.cjs": "research-api.cjs",
    "./window-update-api.cjs": "window-update-api.cjs",
    "./workspace-api.cjs": "workspace-api.cjs",
    "./writing-assistance-api.cjs": "writing-assistance-api.cjs"
  },
  "history-api.cjs": {},
  "profile-api.cjs": {},
  "research-api.cjs": {
    "./subscriptions.cjs": "subscriptions.cjs"
  },
  "subscriptions.cjs": {},
  "window-update-api.cjs": {
    "./subscriptions.cjs": "subscriptions.cjs"
  },
  "workspace-api.cjs": {
    "./subscriptions.cjs": "subscriptions.cjs"
  },
  "writing-assistance-api.cjs": {
    "./subscriptions.cjs": "subscriptions.cjs"
  }
};
const __preloadCache = Object.create(null);
function __loadPreloadModule(moduleId) {
  if (__preloadCache[moduleId]) return __preloadCache[moduleId].exports;
  const factory = __preloadModules[moduleId];
  if (!factory) throw new Error(`Unknown bundled preload module: ${moduleId}`);
  const module = { exports: {} };
  __preloadCache[moduleId] = module;
  factory(module, module.exports, (request) => {
    const dependencyId = __preloadDependencies[moduleId]?.[request];
    if (!dependencyId) throw new Error(`Unknown bundled preload dependency: ${moduleId} -> ${request}`);
    return __loadPreloadModule(dependencyId);
  });
  return module.exports;
}

const { contextBridge, ipcRenderer } = require("electron");
const { createPaperWriterApi } = __loadPreloadModule("facade.cjs");
const flatFacade = createPaperWriterApi(ipcRenderer);
contextBridge.exposeInMainWorld("paperWriter", flatFacade);
